version: "3.8"
services:
  edgedb:
    image: edgedb/edgedb
    volumes:
      - ./edgedb_data:/var/lib/edgedb/data
      - ./dbschema:/dbschema
    ports:
      - 5656:5656
    env_file: ./.env

  front:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - .:/app
      - /app/node_modules
    env_file: ./.env
    ports:
      - 5173:5173
    depends_on:
      - edgedb
